#!/bin/bash

for dir in $(find $REPO_ROOT/packages -type d -not -regex .*/dist.* -not -regex .*/node_modules.* -not -regex ".*/\..*" -not -regex .*__pycache__.*)
do
    if [[ -f "${dir}/pyproject.toml" ]]; then
        echo ""
        echo "install-pyproject: Found Python project in $dir"
        cd $dir
        voff
        poetry install
        if [[ $? -ne 0 ]]; then
            echo "install-pyproject: Installation failed"
            exit 1
        fi
    fi
done
