name: Build and Publish Development Container

on:
  # Trigger on pushes to the main branch
  push:
    branches: [main]
  # Allow manual triggering from the Actions tab
  workflow_dispatch:
  # Trigger weekly (Saturday 14:00 UTC) to rebuild
  # This avoids the common Sunday midnight UTC rush
  # This can help pick up security updates from the base image
  schedule:
    - cron: "0 14 * * 6"

env:
  # Define the registry and image name
  # github.repository will automatically use <owner>/<repo-name>
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Required permissions for pushing to GHCR
    permissions:
      contents: read # To checkout the code
      packages: write # To push packages (Docker images) to GHCR
      attestations: write # To create artifact attestations (good practice)
      id-token: write # Needed for certain login/attestation scenarios

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Tag with 'latest' for default branch pushes (e.g., main)
            type=ref,event=branch,pattern=latest,enable={{is_default_branch}}
            # Tag with the Git SHA (short format)
            type=sha,prefix=sha-,format=short
            # Tag with date on default branch pushes or scheduled runs (YYYYMMDD)
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch,pattern={{date 'YYYYMMDD'}},enable={{is_default_branch}}

      # Set up Docker Buildx for enhanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true # We definitely want to push
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Leverage build cache for faster rebuilds in this repo
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Enable provenance attestations (recommended)
          provenance: true
